services:

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8978:8978"
    environment:
      - CB_SERVER_NAME=CloudBeaver Community
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - minha_network
    restart: always
    depends_on:
      - db

  mysql-exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysql-exporter
    restart: always
    command:
     - "--mysqld.username=${MYSQL_EXPORTER_USER}:${MYSQL_EXPORTER_PASSWORD}"
     - "--mysqld.address=db:3306"
    networks:
      - minha_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: always
    networks: 
      - minha_network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    restart: always
    depends_on:
      - prometheus
    networks: 
      - minha_network

volumes:
  prometheus_data:
  grafana_data:
  cloudbeaver_data:

networks:
  minha_network:
    driver: bridge
